### ISSUE TITLE
Project state

### ISSUE THREAD

**Issue by pedro2555** [donadigo/appeditor#101]
Issues don't seem to be addressed and long reported problems continue to exist.

Is this project abandoned? Is there any other issue preventing support to be continued?

**Comment by donadigo** [comment]
This project as well as Eddy are kinda "abandoned" in that there's no commits happening or real development. They of course will continue to exist in AppCenter and will be also updated when 6.0 comes out. I just have a few things going on like studies and I would also like to contribute a little bit to elementary OS itself, so there's not a lot of time left for these.

**Comment by pedro2555** [comment]
ok, thanks. I will see if I can help, maybe this time I look into vala.
