### ISSUE TITLE
Application does not support dark theme

### ISSUE THREAD

**Issue by hotsezus** [donadigo/appeditor#104]
We should add dark theme to make application look consistent on OS with dark mode enabled.
There is a code reference on how can we do this.
https://github.com/elementary/appcenter/blob/f1a53a3dfc2ae8680940eebffbdbed18038fd1a3/src/Application.vala#L144

If anyone will start working on that, please write in comments. Because i'm also thinking about doing it if i have free time

**Comment by ChildishGiant** [comment]
For me I've just got the prefer dark flag on and it works straight out the box. Maybe a reboot is needed?

![image](https://user-images.githubusercontent.com/13716824/109520523-3e194200-7aa4-11eb-80bd-8a3b4a6ab222.png)

**Comment by AlexDerbenev** [comment]
> For me I've just got the prefer dark flag on and it works straight out the box. Maybe a reboot is needed?
> 
> ![image](https://user-images.githubusercontent.com/13716824/109520523-3e194200-7aa4-11eb-80bd-8a3b4a6ab222.png)

Did you just enable dark mode in settings?
I can't get it working this way

**Comment by ChildishGiant** [comment]
With elementary tweaks I turned "Prefer dark variant" on and it works

**Comment by AlexDerbenev** [comment]
Elementary tweaks is hacky and not official way to enable dark mode.
This issue is more about preparing for Elementary OS 6.0 release that has it's own proper dark theme implementation

**Comment by ChildishGiant** [comment]
Ah I suppose that it doesn't yet work with the prereleases of 6.0 since they're not openly available to test on.

**Comment by donadigo** [comment]
AppEditor now supports dark theme on elementary OS 6.1.
