### ISSUE TITLE
Vala sources licensed LGPLv2+, but no (L)GPLv2 license text

### ISSUE THREAD

**Issue by musicinmybrain** [donadigo/appeditor#106]
The copyright headers in the Vala sources indicate they are licensed under LGPLv2+. Please consider either changing them to match the overall license (GPLv3), if you are the sole copyright holder, or at least add COPYING.LGPL and COPYING.GPLv2 or similar files, with the LGPLv2 and GPLv2 license texts.

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/dfe418851c663b695d5d0f525be100d9f76d3323 and https://github.com/donadigo/eddy/commit/c275089bc7478a62b364fa99a683775aac6325ae. Thank you for noticing.
