### ISSUE TITLE
Not all apps are showed in

### ISSUE THREAD

**Issue by Radical4ever** [donadigo/appeditor#118]
hi, i have this issue when i use the flatpak version of the apps, and the thing is that not all apps are showed in just some of them (mostly debs but no flatpak installed). i tried changing permissions but that didnt solve it.

**Comment by donadigo** [comment]
Hello, I know this is an issue and there's no way for me to fix it right now (and I've tried for a bit) It seems like Flatpak completely blocks access to some files and there's no way to access them, even with all permissions. I'm not sure, but I guess this will require some work on Flatpak first to fully make all apps visible.

**Comment by Radical4ever** [comment]
guess this is going to be a workaround; the solution i found is building and installing the app and whit that it shows them all.

**Comment by Radical4ever** [comment]
i found a solution!. using flatseal y added this to the "other files" box:
~/usr/share/applications:ro; i leave a screenshot for more details
![Captura de pantalla de 2022-01-02 15-04-28](https://user-images.githubusercontent.com/83252104/147885086-e4d8d28b-ed9a-45a4-a059-796c7b224480.png)

**Comment by Radical4ever** [comment]
just adding that now it shows all the apps with no issues.
