### ISSUE TITLE
Add an option to have separate notifications settings 

### ISSUE THREAD

**Issue by PapayaMedia** [donadigo/appeditor#12]
It would be great to have a checkbox for each app to have separate notifications settings and not be included in the "Other" categories. This checkbox would add the following line to the .desktop file:

`X-GNOME-UsesNotifications=true`

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/94f769dd9c5d1d9ded1c51d3d5c136ee201ebe16.
