### ISSUE TITLE
Error when trying to pay for the app on AppCenter

### ISSUE THREAD

**Issue by aral** [donadigo/appeditor#120]
Hey Adam,

First off, thank you for this very useful app. I loved it on elementary OS 5 and I’m very happy to see it updated for 6.

I was just trying to buy it on AppCenter and got the following error:

![Screenshot from 2022-01-03 20-46-05@2x](https://user-images.githubusercontent.com/41798/147979229-00d97135-0305-4369-b8df-d4a0b2bc4f4e.png)

When I encountered this on my own app, it was because the Stripe API Key I had was the wrong one. It’s __not__ the one that you see in your Stripe dashboard for the account you linked.

Detailed instructions here:

https://github.com/elementary/appcenter-reviews/pull/249

Hope this helps + thanks again :)

**Comment by donadigo** [comment]
Thank you for notifying! And I was wondering why no payments went through, fixed in the next update.
