### ISSUE TITLE
The used Gnome runtime is too outdated for Flatpak

### ISSUE THREAD

**Issue by ssmns** [donadigo/appeditor#127]
Hi, I noticed that you are using an outdated runtime for the Flatpak package, here's the pasted output when I update all Flatpaks on my system:

`Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
`

**Comment by thwaller** [comment]
Same here. Posting the next lines, showing this does relate to this app:

```
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.donadigo.appeditor
```

**Comment by ssmns** [comment]
done.
