### ISSUE TITLE
Edits should be auto-saved

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [donadigo/appeditor#13]
elementary OS uses auto-save design pattern by default (See: https://elementary.io/docs/human-interface-guidelines#always-saved), and so this application should too, to avoid confusion. I've edited multiple entries, and none of the changes happened, and I thought that the application doesn't work, but it turns out that I should have saved each item instead.

I think that auto-save should occur when the current item goes out of focus: for example, when the user switches to another entry, or upon application closing.

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/16817da772c98c48d42bedc917dd598096d2b6c7, the changes will be saved when the main window closes.
