### ISSUE TITLE
Please push tags for recent releases

### ISSUE THREAD

**Issue by musicinmybrain** [donadigo/appeditor#137]
Please push `1.1.4` and `1.1.5` tags, which I think should reference aeb0b13e5dfd2dfde951e8f18d9075eee5054f71 and 8612fc8f8f812bc50002d4086afa304228a72cae, respectively.

**Comment by donadigo** [comment]
Indeed I've forgotten to make releases here. Thanks!
They're now released: https://github.com/donadigo/appeditor/releases/tag/1.1.4 and https://github.com/donadigo/appeditor/releases/tag/1.1.5

Closing.

**Comment by musicinmybrain** [comment]
Awesome! Thanks.
