### ISSUE TITLE
Duplicate entry functionality

### ISSUE THREAD

**Issue by peteruithoven** [donadigo/appeditor#17]
In some cases it might be useful to have the possibility to duplicate entries. 

I for example have to manually add entries for Firefox nightly, beta and developer edition, which look alike a lot, being able to duplicate the first one would be great.

**Comment by donadigo** [comment]
I'll look at that when releasing the next version. Thanks for the suggestion!

**Comment by donadigo** [comment]
Added in https://github.com/donadigo/appeditor/commit/5f750eb623b9b3d1c71f1a21b8f3077ccdbd4c45, closing.

**Comment by peteruithoven** [comment]
Thanks!
