### ISSUE TITLE
Creating new application when filtering is confusing?

### ISSUE THREAD

**Issue by peteruithoven** [donadigo/appeditor#18]
There is a difference in behavior when creating a new application normally and when having filtered the applications list. Normally the user navigates to the newly created application and the list view scrolls to that application. But when filtering the list nothing seems to happen, making it seem like it didn't work. Maybe it should clear the filter and do the same? 
![peek](https://user-images.githubusercontent.com/523210/31586630-c2d0eff4-b1d3-11e7-827e-f49d0965c93b.gif)

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/87d004b64bf611e4c6089ef00cb0ac0f0b1d98fa.

**Comment by peteruithoven** [comment]
Thanks!
