### ISSUE TITLE
AppEditor appears to be missing from AppCentre

### ISSUE THREAD

**Issue by qururoland** [donadigo/appeditor#20]
I have two machines, one with AppEditor installed via AppCentre and one not. AppEditor does not appear in either of their AppCentres.

apt search AppEditor reveals:

```
Full Text Search... Done
com.github.donadigo.appeditor/xenial 0.9.5 amd64
  AppEditor

```
but 

```
sudo apt-get install AppEditor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package AppEditor
sudo apt-get install AppEditor
```

the apt caches have been updated.

Could be just me - have not validated it elsewhere...

**Comment by donadigo** [comment]
I don't think this is the issue with AppEditor, try to go to the README here on GitHub and click the "Get it on AppCenter" and see if AppCenter shows the right page. 

As for installing via apt:
"AppEditor" is the title of the package, not it's name. The name is the first "com.github..." string so the correct command to install AppEditor would be:
`sudo apt install com.github.donadigo.appeditor`

Feel free to close the issue or comment further.

**Comment by qururoland** [comment]
I've built it from source in the meantime so am a happy user but...

clicking on the "Get it on AppCenter" shows "no apps could be found"

I have tried this on both of my machines and get the same result. Perhaps someone else could check?

**Comment by donadigo** [comment]
Hm that's weird, I will check that when I'm home but it doesn't seem like an issue with AppEditor. On what distro you're at?

**Comment by donadigo** [comment]
Closing since this doesn't look like it's issue with the packaging or the metadata, feel free to reopen.
