### ISSUE TITLE
Crash when add a new app entry

### ISSUE THREAD

**Issue by zhutmost** [donadigo/appeditor#22]
When I add a new entry, it crashes and then quits. Here are logs.

> [INFO 23:52:59.660469] Application.vala:153: AppEditor version: 0.9.3
> [INFO 23:52:59.660493] Application.vala:155: Kernel version: 4.10.0-40-generic
> [DEBUG 23:52:59.683530] [Gtk] Connecting to session manager
> [INFO 23:53:20.575511] [Gtk] GtkDialog mapped without a transient parent. This is discouraged.
> [INFO 23:53:26.221473] [Gtk] GtkDialog mapped without a transient parent. This is discouraged.
> [INFO 23:53:45.851157] [Gtk] GtkDialog mapped without a transient parent. This is discouraged.
> [FATAL 23:54:07.616323] [GLib-GIO] g_app_info_get_display_name: assertion 'G_IS_APP_INFO (appinfo)' failed
> [FATAL 23:54:07.616388] string_strip: assertion 'self != NULL' failed
> Segmentation fault (core dumped)

**Comment by donadigo** [comment]
This should be fixed with https://github.com/donadigo/appeditor/commit/87d004b64bf611e4c6089ef00cb0ac0f0b1d98fa. Closing.
