### ISSUE TITLE
Several bugs with: Add new entry, Delete entry

### ISSUE THREAD

**Issue by saitam1** [donadigo/appeditor#26]
Bug 1:
If I click on `New entry` the entry is added into `Other` category, no matter if I have clicked into another category right before.

Bug 2:
If I click `Delete entry` right after creating it (before typing anything else into the entry and before moving into another entry), it will still show the deleted entry in the category section with no content, but it will NOT delete it. See screenshot:

![appeditor](https://user-images.githubusercontent.com/23245678/34319763-41180392-e7ea-11e7-943f-8cfb35c524c3.png)

**Comment by zvirdaniel** [comment]
I also have this problem. However, this happens to me only after I save a change in another app. Example: I change the name of Files, save it, and then I can not create a new entry properly, because I can not edit it.

**Comment by donadigo** [comment]
Both fixed in #https://github.com/donadigo/appeditor/commit/de589e89b29ec8899ce43c0be0e8b2b2578ced56, closing.
