### ISSUE TITLE
Russian App names

### ISSUE THREAD

**Issue by ariant-web** [donadigo/appeditor#29]
Elementary OS Loki 0.4.1. After saving russian names are converted to incorrect text.

![appeditor](https://user-images.githubusercontent.com/20294256/35437605-ed031c0c-02b4-11e8-8256-d40a09177633.jpg)

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/0488d03bed74bafee70e1c6382af24abff3723be, thanks for reporting!
