### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by SpxterWohlf** [donadigo/appeditor#31]
I don't know I think I might need to purge it but I don't know the package name. I tried searching the package manger for it but I did not find and thing. I think I did something and I can't open it, or it will open but I can't do anything. I create my own launchers for games with a special script but I cant make them if it crashes.
I don't know where to find logs. Still new to linux.

**Comment by donadigo** [comment]
What OS are you using? If elementary OS, you should be redirected to the right page in AppCenter by clicking this link: https://appcenter.elementary.io/com.github.donadigo.appeditor, if not the package name in Ubuntu based distros is `com.github.donadigo.appeditor`.

**Comment by SpxterWohlf** [comment]
Hi This is a very old issue and is irreverent now. 

I am closing this.
