### ISSUE TITLE
Can't rename Inkscape

### ISSUE THREAD

**Issue by artemanufrij** [donadigo/appeditor#4]
Hey Adam. It's a very helpful app! Thank you!

But, I can't rename `Inkscape Vector Graphics Editor` into `Inkscape`. App shows `Changes successfully saved` but content of `.desktop` file hasn't changes.

**Comment by artemanufrij** [comment]
`.desktop` file in `.local/share/applications/` hasn't also any changes

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/e22536cc15dca28afcbed989365a1081669e0607.
