### ISSUE TITLE
How to fix command not found?

### ISSUE THREAD

**Issue by orschiro** [donadigo/appeditor#40]
Hey @donadigo,

Just found this problem. Wanted to create a desktop file to run a command line command `flatpak update` which works just fine in my GNOME Terminal. 

However, appeditor tells me it's not a valid command. 

Any ideas? Maybe because I am running the sandboxed flatpak version?

Thank you!

![screenshot from 2018-02-23 11-35-08](https://user-images.githubusercontent.com/170947/36590128-e2546d26-188d-11e8-9201-474fb0a453a7.png)

**Comment by donadigo** [comment]
@orschiro hello! It might be, does this happen if you enter other executables as well? Also, could you tell me where the flatpak binary is located on your system by doing `which flatpak`?

**Comment by orschiro** [comment]
Hey @donadigo,

Other commands seem to work fine.

```
[orschiro@localhost ~]$ which flatpak
/usr/bin/flatpak
```

![peek 2018-02-23 16-38](https://user-images.githubusercontent.com/170947/36602333-10824c84-18b8-11e8-811d-7e6a571833c6.gif)

**Comment by gort818** [comment]
Does the full path to flatpack work?

**Comment by orschiro** [comment]
@gort818 nope.

![image](https://user-images.githubusercontent.com/170947/36602672-e231b40e-18b8-11e8-97da-b215cb731a14.png)

**Comment by harrymilne** [comment]
Having this issue too.. kind of defeats the purpose of this application...

**Comment by donadigo** [comment]
Are you all running AppEditor sandboxed with Flatpak? If yes, then this is a Flatpak packaging issue, and not application specific. AppEditor probably doesn't have access to / and it fails to recognize the file. This has to be fixed in https://github.com/flathub/flathub.

**Comment by bilelmoussaoui** [comment]
Will be fixed with the next update to v1.1.0. Can be closed here

**Comment by donadigo** [comment]
@bilelmoussaoui thanks!
