### ISSUE TITLE
It misunderstands accentuation on edited entries.

### ISSUE THREAD

**Issue by hdmjunior** [donadigo/appeditor#48]
When you save changes to any entry where the name or description has been modified and includes accented characters, like "á" or "ê", the application changes the typed result, showing things like "\303\241" or "\303\252" instead.

However, there seems to be no problem with application entries whose name or description already uses accented characters by default.

**Comment by donadigo** [comment]
This should be fixed with commit that I pushed a while ago: https://github.com/donadigo/appeditor/commit/0488d03bed74bafee70e1c6382af24abff3723be

**Comment by hdmjunior** [comment]
Oh, nice! Thanks for reply :))

**Comment by donadigo** [comment]
Closing I guess, if you experience it after the next update, feel free to reopen.
