### ISSUE TITLE
Appeditor Installed from flatpak on flathub cannot see my menu entries

### ISSUE THREAD

**Issue by stuaxo** [donadigo/appeditor#50]
I guess there is some sandboxing that stops it editing my menus ?

![image](https://user-images.githubusercontent.com/179677/39127774-e9af043e-46fd-11e8-8533-047d915f2e2b.png)

It only sees a minimal menu with itself on it.

OS is Ubuntu 18.04.

App was installed from the Ubuntu Software app, but on flatpak.

**Comment by Wowfunhappy** [comment]
I'm getting this as well! The only entries listed in the menu are AppEditor itself, and "Help". I don't know why the Help app in particular appears correctly.

I also installed the app via flatpak.

**Comment by stuaxo** [comment]
BTW @donadigo thanks for writing this, even if it doesn't work for me right now; I've had high hopes for a new menu editor for years now, so it's great this exists :)

**Comment by donadigo** [comment]
Installed Ubuntu 18.04 on a VM and can confirm this. It looks like it was actually an issue while making the app available on FlatHub , and it seems like the repo maintainers solved it there (https://github.com/flathub/flathub/pull/266#issuecomment-366515553) but it still doesn't work. I can also see that all the permissions they gave are correct and in theory should allow AppEditor to access the entries on the system, but somehow they don't. Needs further investigation here I guess.

**Comment by suckybell** [comment]
Same issue here on Fedora 28.  Everything was there when I built from source.

**Comment by bilelmoussaoui** [comment]
Please open this issue here instead https://github.com/flathub/com.github.donadigo.appeditor/issues/4

**Comment by bilelmoussaoui** [comment]
Will be fixed with the next update to v1.1.0. Can be closed here

**Comment by stuaxo** [comment]
Great, works for me !

Thanks.
