### ISSUE TITLE
[Enhancement] Contractor to add menu entries from file manager

### ISSUE THREAD

**Issue by Juankz** [donadigo/appeditor#52]
With the aim to improve usability of linux desktop I would like to suggest a contractor to add applications entries to menu easier. Would be something like this:

![proposal](https://user-images.githubusercontent.com/18577412/40814388-9268ce32-6505-11e8-82a0-d93090171eed.png)

Reference: https://github.com/elementary/contractor

**Comment by donadigo** [comment]
That's a great idea actually, thanks! I'll see if I can implement it in the next release.

**Comment by donadigo** [comment]
Implemented in https://github.com/donadigo/appeditor/commit/1a210fbea99b8314aa2ac0a8bcd75bcc2df7fd01, closing.
