### ISSUE TITLE
PWYW button in AppCenter?

### ISSUE THREAD

**Issue by wout** [donadigo/appeditor#68]
Not an issue really, just a suggestion. Please put a pay what you want button in the AppCenter. I find this one of the most useful apps form the elementary OS AppCenter so far. I'm coming from another distro where it was a lot of work hiding certain apps from the launcher or manage commands and icons for others. So I'd be glad to pay for it. :)

**Comment by donadigo** [comment]
I'm sorry but unfortunately Stripe isn't availabe in my country so I just can't set it up here right now. Currently AppCenter doesn't support anything than Stripe, but I would be open to e,g setting up a PayPal account for this (if it is supported).

**Comment by wout** [comment]
That's unfortunate indeed. Maybe you should put up a **donate** button here in your README.
