### ISSUE TITLE
Hide hidden apps still shows too much

### ISSUE THREAD

**Issue by ovdeathiam** [donadigo/appeditor#8]
I see you've implemented the show/hide hidden apps as suggested on Google+. Great job!

The hide hidden apps state still shows more items than what we can see when using applications menu.

Some examples are:
- htop
```
Terminal=true
Categories=ConsoleOnly;System;
```
- gnome-power-statistics
```
OnlyShowIn=GNOME;Unity;
```
- evince
- unity-control-center power, unity-control-center region
```
OnlyShowIn=Unity;
```

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/a9b372e379f3ab0f757eb71aea8830d2b58aa993, will be available in the next release.
