### ISSUE TITLE
2,6 GB of disk space required?

### ISSUE THREAD

**Issue by Marek-Moehling** [donadigo/appeditor#86]
Seems like something is going wrong, when I download the zip it's only 225 kB. Any Ideas?

![Selection_001](https://user-images.githubusercontent.com/15626163/67250043-27072080-f46a-11e9-8519-4fc4fb69e432.png)

	Running LinuxMint Linux, the LinuxMint 19.2 (tina) release.
	GNOME: 3.28.2 (Ubuntu)
	Kernel version: 4.15.0-65-generic (#74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019)
	GCC: 7 (x86_64-linux-gnu)
	Xorg: 1.19.6 (03 June 2019  08:10:35AM) (03 June 2019  08:10:35AM)

**Comment by wyphan** [comment]
Most likely it's trying to install flatpak version of GNOME environment. You can confirm this by installing through the command line:

```shell
sudo flatpak install flathub com.github.donadigo.appeditor
```

For me, it gives the following output (Ubuntu 20.04 LTS (focal), GNOME 3.36.2, Linux kernel `5.4.0-29-generic #33-Ubuntu`, GCC 9.3.0, Xorg 1.20.8). Notice number 5 and 6:
```
        ID                                        Branch Op Remote  Download
 1.     com.github.donadigo.appeditor.Locale      stable i  flathub < 128.4 kB
 2.     org.freedesktop.Platform.GL.default       19.08  i  flathub  < 85.1 MB
 3.     org.freedesktop.Platform.GL.nvidia-440-64 1.4    i  flathub < 102.0 MB
 4.     org.freedesktop.Platform.openh264         2.0    i  flathub < 916.8 kB
 5.     org.gnome.Platform.Locale                 3.34   i  flathub < 322.2 MB
 6.     org.gnome.Platform                        3.34   i  flathub < 320.4 MB
 7.     com.github.donadigo.appeditor             stable i  flathub  < 23.4 MB
```

**Comment by donadigo** [comment]
Yes, it's one of the properties of Flatpak apps, even though after installing the base Sdk it should be reused for other apps as well. Closing.
