### ISSUE TITLE
Not first category displayed

### ISSUE THREAD

**Issue by ovdeathiam** [donadigo/appeditor#9]
Apps like audacious or audacity have these lines as categories:
Categories=AudioVideo;Audio;Player;GTK;
Categories=AudioVideo;Audio;AudioVideoEditing;

Both display under Audio in appeditor, but under AudioVideo in wingpanel in elementaryOS

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/appeditor/commit/6c635d483a9cfe36f18eb54704fa15bc6e8d77d4, closing.
